### ISSUE TITLE
Cant get SPI mode to work at all.

### ISSUE THREAD

**Issue by strid3r21** [sparkfun/SparkFun_STHS34PF80_Arduino_Library#7]
I've tried everything i can think of. multiple ESP32 boards, multiple sensors. made sure the CS bridge is fully cut. 

the sensors work in i2c mode, but not spi. 

is there something I'm missing?

**Comment by MadisonC-SparkFun** [comment]
Hello! 

When working with SPI, try using this circuit: 
![STHS32PF80-SPI-support](https://github.com/sparkfun/SparkFun_STHS34PF80_Arduino_Library/assets/111776413/1e7d8d43-94ed-48be-a003-e19988879bc2)

I was using the ESP32-WROOM Thing Plus C and the STHS32PF80 Breakout. Give this circuit a try, and let me know if you are still having any issues with this.

**Comment by strid3r21** [comment]
> Hello! 
> 
> When working with SPI, try using this circuit: 
> ![STHS32PF80-SPI-support](https://github.com/sparkfun/SparkFun_STHS34PF80_Arduino_Library/assets/111776413/1e7d8d43-94ed-48be-a003-e19988879bc2)
> 
> I was using the ESP32-WROOM Thing Plus C and the STHS32PF80 Breakout. Give this circuit a try, and let me know if you are still having any issues with this. 

Thanks for the tip! Just so I'm 100%, are youconnecting both the MOSI & MISO to the same SDA line, just with MISO connected via a 1k resistor?

**Comment by MadisonC-SparkFun** [comment]
Yep, that's exactly it!

**Comment by strid3r21** [comment]
> Yep, that's exactly it!

Awesome, I'll give that a try tonight and see if that works! It's much appreciated for your help!

**Comment by strid3r21** [comment]
ok, that still doesn't work sadly. tried different ESP32's and multiple sensors again with no luck. 

current wire setup is as follows. I've tried a handful of different wiring configurations as well incase i was just miss understanding the hookup. nothing works :(


STHS3 
SDA     ->     ESP32 MOSI + 1k -> MISO
SCL     ->     ESP32 SCK
CS       ->     ESP32 CS pin (user defined)
3v       ->     ESP32 3V
GND   ->     ESP32 GND

**Comment by MadisonC-SparkFun** [comment]
That looks ok on my end - could you also send over your code so I can see if anything raises a concern there?

**Comment by strid3r21** [comment]
> That looks ok on my end - could you also send over your code so I can see if anything raises a concern there?

its just the default example code.

```
#include "SparkFun_STHS34PF80_Arduino_Library.h"
#include <SPI.h>

STHS34PF80_SPI mySensor; 

// Presence and Motion variables to fill
int16_t presenceVal = 0;
float temperatureVal = 0;

// Set your chip select pin according to your setup
uint8_t chipSelect = 3;


void setup()
{
    Serial.begin(115200);
    Serial.println("STHS34PF80 Example 4: SPI Functionality");

    // Configure the chip select pin
    pinMode(chipSelect, OUTPUT);
	  digitalWrite(chipSelect, HIGH);

    // Begin SPI
    SPI.begin();

    // Establish communication with device 
    if(mySensor.begin(chipSelect) == false)
    {
      Serial.println("Error setting up device - please check wiring.");
      while(1);
    }

    delay(500);
}

void loop() 
{
  sths34pf80_tmos_drdy_status_t dataReady;
  mySensor.getDataReady(&dataReady);
  Serial.println(dataReady.drdy);

  // Check whether sensor has new data - run through loop if data is ready
  if(dataReady.drdy == 1)
  {
    sths34pf80_tmos_func_status_t status;
    mySensor.getStatus(&status);
    
    // If presence flag is high, then print data
    if(status.pres_flag == 1)
    {
      // Presence Units: cm^-1
      mySensor.getPresenceValue(&presenceVal);
      Serial.print("Presence: ");
      Serial.print(presenceVal);
      Serial.println(" cm^-1");
    }

    if(status.mot_flag == 1)
    {
      Serial.println("Motion Detected!");
    }

    if(status.tamb_shock_flag == 1)
    {
      mySensor.getTemperatureData(&temperatureVal);
      Serial.print("Temperature: ");
      Serial.print(temperatureVal);
      Serial.println(" °C");
    }
  }
}`

**Comment by strid3r21** [comment]
i get this error with that code.

im using an ESP32-S3 btw if that matters at all.

```
 Compilation error: no matching function for call to 'STHS34PF80_SPI::getDataReady()'
![Screenshot 2024-02-28 185307](https://github.com/sparkfun/SparkFun_STHS34PF80_Arduino_Library/assets/56952812/45adcedc-91ee-4184-8bd6-4c2ac656a881)

**Comment by strid3r21** [comment]
that doesn't work either. 

so far I've tried all these examples (of which i appreciate!)
multiple ESP32-S3 dev boards
different bread boards and wires
multiple of the sensors. 

but for some reason i cant seem to understand, the sensor fails to initialize in SPI Mode. the CS jumper **IS** cut. 

if CS jumper is connected, then I2C works fine. 

but I'm really needing to run multiple of these at the same time and SPI mode is the only way i can see that working.

**Comment by MadisonC-SparkFun** [comment]
Hello again,

After doing more testing on my end, I am able to use this with no issues. At this point, I'm going to send you over to the SparkFun forums and I am going to mark this issue as closed. There you can get help from our support team and the community. 

https://forum.sparkfun.com/

**Comment by kent-williams** [comment]
The SPI example is not working for me as well. I'm even using the RedBoard Plus.

```
#include "SparkFun_STHS34PF80_Arduino_Library.h"
#include <SPI.h>

STHS34PF80_SPI mySensor; 

// Presence and Motion variables to fill
int16_t presenceVal = 0;
float temperatureVal = 0;

// Set your chip select pin according to your setup
uint8_t chipSelect = 10;

void setup()
{
    Serial.begin(115200);
    Serial.println("STHS34PF80 Example 4: SPI Functionality");

    // Configure the chip select pin
    pinMode(chipSelect, OUTPUT);
	  digitalWrite(chipSelect, HIGH);

    // Begin SPI
    SPI.begin();

    // Establish communication with device 
    if(mySensor.begin(chipSelect) == false)
    {
      Serial.println("Error setting up device - please check wiring.");
      while(1);
    }

    delay(500);
}

void loop() 
{
  sths34pf80_tmos_drdy_status_t dataReady;
  mySensor.getDataReady(&dataReady);
  Serial.println(dataReady.drdy);

  // Check whether sensor has new data - run through loop if data is ready
  if(dataReady.drdy == 1)
  {
    sths34pf80_tmos_func_status_t status;
    mySensor.getStatus(&status);
    
    // If presence flag is high, then print data
    if(status.pres_flag == 1)
    {
      // Presence Units: cm^-1
      mySensor.getPresenceValue(&presenceVal);
      Serial.print("Presence: ");
      Serial.print(presenceVal);
      Serial.println(" cm^-1");
    }

    if(status.mot_flag == 1)
    {
      Serial.println("Motion Detected!");
    }

    if(status.tamb_shock_flag == 1)
    {
      mySensor.getTemperatureData(&temperatureVal);
      Serial.print("Temperature: ");
      Serial.print(temperatureVal);
      Serial.println(" °C");
    }
  }
}
```

@MadisonC-SparkFun Can you share the exact setup on the Redboard Plus please!

**Comment by sfe-SparkFro** [comment]
Hi there,

I'm also seeing this issue, with both an ESP32 and RedBoard Qwiic. I poked around at some things and I don't have a fix yet, but there's definitely a problem with SPI, so will re-open this until it's fixed.

**Comment by kent-williams** [comment]
@sfe-SparkFro and luck yet?

**Comment by sfe-SparkFro** [comment]
Apologies for the delay on this, been a busy month for me! Finally got back to this and pushed a fix.

Looks like this SPI driver was copied from somewhere else, and some necessary changes weren't made. See https://github.com/sparkfun/SparkFun_STHS34PF80_Arduino_Library/commit/057054230e0867c3c0b2ca802e8937e14b9012c0 I only did the bare minimum changes to get Example 4 working on my end with both an ESP32 and RedBoard Plus, I'm not confident whether this implementation works on every method (I don't have time to test that right now). But hopefully this is all that's needed!

I've closed this in the hopes that SPI is all happy now, but please feel free to reopen this (or a new issue) if problems still exist. Thank you!
